version: '3.8'

services:
  openclaw:
    build:
      context: .
      dockerfile: Dockerfile
    image: docker-openclaw:latest
    container_name: docker-openclaw
    ports:
      - "18789:18789"
    volumes:
      - ./config/openclaw.json:/root/.openclaw/openclaw.json
      - ./workspace:/root/.openclaw/workspace
    environment:
      - TZ=Asia/Shanghai
      - MINIMAX_API_KEY=YOUR_MINIMAX_API_KEY
      - ALIYUNCS_API_KEY=YOUR_ALIYUNCS_API_KEY
      - PRIMARY_MODEL=aliyuncs/qwen3.5-plus
      - PRIMARY_VL_MODEL=aliyuncs/qwen3-vl-plus
      - WEBCHAT_TOKEN=WHAT_EVER_YOU_WANT
      - FEISHU_APP_ID=YOUR_FEISHU_APP_ID
      - FEISHU_APP_SECRET=YOUR_FEISHU_APP_SECRET
      - QYWECHAT_BOT_ID=wecom_bot_id
      - QYWECHAT_SECRET=wecom_bot_secret
    restart: unless-stopped
    networks:
      - openclaw-network

networks:
  openclaw-network:
    driver: bridge